apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds: ["Pod"]
      exclude:
        any:
          - resources:
              namespaces: ["argocd", "kyverno", "kube-system", "argo-rollouts"]
      validate:
        message: "Toda imagen debe declarar un tag explicito (repo/imagen:tag)."
        pattern:
          spec:
            containers:
              - image: "*:*"
    - name: validate-latest-tag
      match:
        any:
          - resources:
              kinds: ["Pod"]
      exclude:
        any:
          - resources:
              namespaces: ["argocd", "kyverno", "kube-system", "argo-rollouts"]
      validate:
        message: "La etiqueta ':latest' esta prohibida."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
