## Contraparte de application-secrets-dev.yaml para sa-p8-prod.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform-secrets-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: sa-platform
  source:
    repoURL: "https://github.com/AlejandroPA21/sa-platform-gitops.git"
    targetRevision: main
    path: secrets
    directory:
      include: "*.sa-p8-prod.sealed.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
