---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    .dockerconfigjson: AgA309eu7dsTVphvj5trvscNE9uBNPXUXsnnCw3vP84w3Ls8uqDr5A/gPBOlZRtWYgRegCpXdMFKU8VgvSZsiCHdgeXrqvrGA8lg9Z4NgYatZNSCLitSNpdu2AUdJOpfbkKMfoBsHyx93B8zQ8vpoHf/sgwZYdcyVr2CoPX56gW4s73f3UQBqD4EEiNXxlVnB7VZCOvioPzbECHOhZLfvc1NH0B73XlWPejvwtdjCizgvQ4g9x5jLWLthGnus2CYbRKQ5IsG5WOtOP7QW6ZtMBeOmYCnOZHH6Cfr3COS0g30ccniPNW2z1jqjMC//cDGuFkYOIUH/rUT1yVsuqcUTpOrtOUdQtDTAAk9CuzEpUDmm6Vig/SKfyl+sZb49btU1gQnxPB5s+5mKBIoXsG0C8ALnuEySRU6MzSzVhRWoegzdkEndErZ/SWxSoeZgZSF8xIBpE5WAMIPaBlHsFMnMtuooMkYQ5/8v7FgX455nqDvX6WXgQBaR2VH55Te5rWP3aiuynsO+2VwJuLKNt5qKy27hzqjB0rJZGDTdzeRibaK7DeAEeTqHpzGZkVsN/hIk3ChoLB7irHcFSxPonirL6annNgcU/SCssfujTOV/4cq83xt4LjPq4qfX8EBZZojbhKNyWqCL5XuBBFHyIYwWtiUrD1we3CWPSprXx26Y8Lg9yEUOEmb7y2De/D13CcNlCrAi3BQfRSKNxpNfOtd2qkO7MEg69LXX/rELlG8wuhJ5Mrnz3Gnyv7ztDiiF0Vfy3A4QHLaqGq2F8hOZBzWDs8vVqwB21okQ5Xg9dd/1ngI7CDt/GnCoTc4OiEctLf3j5hx0XBYuVXQPPZFTq6A7BNczwMAx21ZoJZkNzc7aIUi2zotfZP30iLZ2O79ybsJuM6mwk+TwAdAk1qg8mLH/9+MsGe3Bfb6J+1RPjnPjWl+FEsSSIBBwo04aHxWAP+MJVuVv6SsVWll5rdL9p2ZakcW9tT+sUm2sazeqNm1k43Z
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-prod
    type: kubernetes.io/dockerconfigjson
