---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBi3SDdr8ivebxAbZGomMpQrCe4vaAg0G0rCMMLIsvGaWY416Ohz1Ie+XB064XNvGLL4/uEpyiarcGCdtgib2XhxF1DcNFbeHQsxCrmqLbx7yMqk+ktrCjHUt5FXn3nqjVZdDjth30ap1CVh0rczKQK/XMHMP4zjKR4F/PxmiRrVNcWvUVLInPfXWsEiXX9b8/VH3V0r7GUZxKNuc36FHu7f5EvOX50ecPwJMh8tcojscXxVEFShWHedvjhLWobDNmGn6EKAym4HEhsQ/RrPw8sOexIv0IKA8mOuuSkzwxJf8Vd4ZuVLpUfYIglvu47GYYlA8WyDH4oWkL3hbqUsohuQWmyqv3X5zJxuaaoaZOo6wDN1RQje/q9Zlu3QFVbGuFJVDwI5Xp1/PGoJEJt4xOHTe2r2Y6qgOcjWKSiVCVZm/eo7BAQlbsdh+weM+hlsWX7r5nqvJx5weDpOCn6DHFvzs7eYodXzKljjeIUGVzPY+SJxGZj2WkSv8zeIwmqnU/ei48GFTnHbSO8p8/ReU1cICPynaMY2ux0RB0Zy4JPaJJSvG2nYJtuAwSbDlnQZ6uXbJo77twlnG2Zm7tS7pWfx/LYk01+6zNzv3BjGlLnjESu8K7bhADgJWPEUonPTtGC1YXd3o57Qp2PS/6Bt4Z4qEeVDTRdBlr9ECa5w6yedSNtR9Le1t4U2BZnbgcPZ3CgX4XsRRre6rGAaevHLTxYDf5zsA7600usfXGV7ktmlcJCA7CEfIPwZBmObBiBjkIMUNMMSJ5xYrdWfEuzkNOCgPk66ZDt4gH/zvU1a2duIXaGWJ3kKQTG/My15rO8mYn3DAlGzI49jift7SgLfFYI3pFgd+lZ5Ntr9JLMqCanB6cm5gYTqHccdOYeFSjVYo76nEQuQJYVCu2jESZayMSkNUyRq0ytLPaMLDlN4qRfzd4tFQcI4vtXnvY=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-prod
    type: kubernetes.io/dockerconfigjson
