---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCMBG/nlq95H68HyK9OsG2hkSvjTxp6pWyDMrpxuYTcHvlVbkonoae32lmJIAeVpwxjMZ1Glr+k9r9t7Uf0/DvVTIhegXHhz4Ub51RBS7IcIPov6YoOK8V12UH7JumNmtT2cXy3ym2KIiVIECG9xjKvhLFeVV5j0T3wXsHV5AOwl2TgZELWRr/DE47Fy9Y5SH8+84DA8FuHldoqXBPPwsTNvJ72zruWs4+GkaqtYcyFnEl54SnjdRs1GbkNDhFJAUqSJfkStA92ZcuWRTTODS29I/mqvjjpAef9XLpMTtTqw7qtnS/wfU3PKk4boSos6xKrlTgQvQ6OutUYBtuD+MBZhOrHbNAQ6V9embF0tJ5zfAusb1vFdSyVSNmuKwYHpNa2sgldC62tSOtJpLOZi7sZwXKZ2E4Q3bot/c/FYFyYmKYiSHI7pGESLuRimR2WBiTyt723Fr4gVuH/beYOh1LOHel7CUkebtl6PhIyTii/X5pBDN0hnno9Vkl7gad74sxiKLQqCG61jREuQuGxVfb/NrEp+avMXEu4EQadr71vlbi2ObC3bO8zSswUu+Vd//iBj06LaE2CsHfJu2y93Oai44lJeT+yJJYyQi5tQC0GjQapfM10K4CvW0nxU7yzqZwi1xX0fV+m0WwYZd9Eea5/ksIuLEMZttd7q6bw+XAKT5cnYQJFyeAxUn6OgkQqg/rkyvam+nCpivPPXTsqIFiOMAP0fRWA3mmiYGsFzD803Wb6ZJT6v82nmcvuQiOyL9eMIoxNvxMPs2086fYmNa6ZDHLZySz9Db5BVEqT65uuEmdjs5/oLzF9bzu+31BxSgq3SROucPFnxL9X+5Il4wK16GMc0SYIJ4618BECCgku1kl6s+7vj2QWksfmfLeNQYknxNjHYVyXOyQe2cS+//gO/hlZLLKWr7iriWVjiQjVWKN7lukqbNf5gi5cr2fvbBEJO3VYce4dGbGIwCeJZf/8o9AxphXQluu6zeCon6FB
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-dev
    type: kubernetes.io/dockerconfigjson
