---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBpV47+RCKSgNEiNFq93cfVl1dbGQpsCgRdlUWvJSa9b4EUSoNeh5L5cbNMXHvjALhCeW/AIXqym5taQlvtPNd5+m0kyWDe66TyKVhfjS2/gLAJrtotwAIcCytqxMBi8YIlrEWCp9/XodRLEkwYMdnroJAn6Pc31hd5cD3aSYggkn5HILGUFq9fRhnNOQ3WqltO9aVow/uxUQc0WXG1DeA2DIAHweTqaBUfonN4tdZk0KOJl3itOUUVjlDOMfy/kE9kUbSqU0P+6XS93ZZKLCHJtblY4OetgE/iOWPm28gf6bPa1F7kHs6aKFwnKJUqbRZPIntu11qCeiiI5P1uQDXDyYmYoRwj1K98LY251aFQ8MJ49FrPX0XThAEbiBqoD/KnHIpxoMRrlLDLCo217b96EBILKXeMrfIL0mNGa8cwYIDNXxQmYsKz27om7dthUTEAcmTOExkX5HKqXeYG/SfYOIslTvOACrw9gXDX7C+3GcrhcniwuE+6hdhr9ilxaGP7XsTSQ1xF1F9PjFU7GV+1YkPkGr/LlawE4Mterd49RKQofbBHBlDo+WWr4m5GXoL3M9IAx+vUffbstKIuNxc5tsuIjcSpqghaLjc3tG+e+KC8pEsi6BsuDyk7brfxpR1amsOPJwRBy7gnFLDKsql9tUsBStEDzQF8iJbigzPtvPZ4I4Cbv/A6QmoPVlwwpqFaxSTCts17VxsWokJViQ8Vf2G5d46wDQHk1JkV5B/oPJIbXdarh5N5lS4AVEmxDSVrTSLggKRWMkzt/afetUUF4YBudTiOd9m5PCoQWz0rvL1ErXgd4CIr+lg4WXar+guqRbZBVw1Ka5a7D6ImecUuibBGqy4np1/5kE/EtKpxI2UcvL1Jl0XV+OD5svksxsx0GmbdTKD+aHMSTaWM3lx/1UNED6MVUiuXusGmjfuHqC+clI+Zce3ZlAk=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-prod
    type: kubernetes.io/dockerconfigjson
