---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBH3wnLMQw1Bfl6RBSF7MTn01YJ7WwuZUkvMBBvfoE0igToS0rjfd83lTJ5eWFWHfi2AGF8vNaiURakHjVfAsyOsFMQaLvjdqbQw7PfRsWwEUPEMA9fc3dhiuslLduaB7IS+5ditZ0X/nElAhnuhfotnrd4LGf285FFWOQ/Z0bKuXEWkMunYyYCkKTu5GdkTPopJMAkDkoVAepw3DIcgXFim2obowfz5/LBsKBKc45vr6ymi2crwzgJY2yhnwalS1Ev0/frZktcgP0QjtrzsUYvDChJZ0j0xTGFfbyFyANJ26jRc/VRx1UXX/v9dmY/JyetsyW4iUWza+zIOPOXERwFs4N+mOxfJ3yf0Z5Ibz2T6IP0qmQyU1iRu5DDZmXXeSj0LL6yj3vt+OJcIqmOY8TAKrYU+X6Stsu8Hunarujy2ur/EpiG710sH80Es8J9av3BFe5xtdQGlotK3A8bi1uP5uXC4azxoLHpvq0O1A34lhaAh1V07Q7+hXEpe7N8QGlesUszGSYhwwTQIr16zYtG940ZIuKUYNypipppXHEbr9iWXtWwz1HSkYIs1eEZ+YPiUb3E7Ah5bHET5KD8BJwmm4xVggd0FDNZfxJ255ZZdqHGW4ufXHiMpyfWbeskKf/iCgc1ktjnXHp72TRCyqVkjrI8SEDes0vJXebPY8uZrZqdtEdgGJidrEVcF+UOihtR/a+/6rDTGc7rATqcfZ/py1HMET+q6txvuh+SpxUuXx5uk+F/GSE3rVLD0iybvNQnYaNKfDNMbXtwNsn/m70WexXQvYPeM7ma5qppCbWLWmHMsjPUsxsCUF7hwEDEB+eRAa5GRSlkk3T/kM2PLflDqndZni14ru5JfQj7TvsyhbWFnTQKXYEkWHDGWNbRJAVmXgw64g1+6fNiD6Fan0pkODPMUICicYo27e6NhLne9Yz8vpkmXHHrNXw=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-dev
    type: kubernetes.io/dockerconfigjson
