---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCu/8pPQJwrLTh/FIvvHNmcAZ3mh6Ir4VPD5qSfk4LzdE757ByfO8RVysQfuM21xMPh8KS21wD3hVpCxkT4/KOPjVU1BZsmwC9fpjZxWebNa5HWiwrPSnfGG3X+b9HTg28tOkpiRjjoekO7rS2YwGNj9b/ZxdXvr45dfmAo6zSoZo47UHSrsnke89dZ35m+M23TdaHQQpKttX2TFQIKykY9XxG2XLxFfsh6dwYf8sHIQc0M5AW/uZSBZ5yZH8Rdt6g2v/8Xk3aBxtHpst0FjTchuaW6jHhSPeXGlh3gHN+GbwU4XPXvhTEyBrpCdlqK684qjZAx7dZpQHMvD26cF2ozwRTkxFyojEk0cIepvrpEXqNCGCVDuUgqZpGJqMuxOPKQMXT1/vDJ6ZDN1caCmfRF1h28gFv9tvgPhDXBmnqNV/4q7XTJTjXdF8MZ1/FrHHopAKiBfZg7LMS9mVdCWX/H2VniVmfIYgcTJCcgBDh7Hny0sahpa3i8+I+dX0b21lerqAPUS0QKD3ljuU7u/eeZ34w/gFDLjHLD4X5Xa8j+p7+KuF3GSMKSMjggQ+YdEQ7lD0qx1vH0bFQ4nhZumAnjcFKYfSi/ELygiWfZz+q9LYHILM+4uVmxh4BJ+8WmhyWPly52nCcpBL531hi6/Y8cN9/5jf567gsTT9VJG4GkAAuFXluS91foBk76ByP7zf8gg3KiAc0aluHtthcsV+NB2soHYtu9XkD5zBlw5u+kM5alU73gI6JGPOU/yzlWvf84xnaGy4ZGEmJR03bZthxw3y5924pK6UtvSxi+zsaoh+J2th5vSf3v48C2TyqhzQ0n5NkQDqgpW0LparaW1MIMhD1t2q5mJAAvhd261zrAbCbML2kPVds4k5B+u7hisGThxp4QEYZdulxsIuVIKMmzKuEMtyXheONu+2K9JHBi6Y4+jBhW7tHGKxA=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: sa-p8-dev
    type: kubernetes.io/dockerconfigjson
