---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    DATABASE_URL: AgCqmPJIH4oE9DGsa/zaCiwjBkFWaRwU1uDJ6nwoQLEJsNkJGBUEOlQHmvEzlJOGCWafA+RiMA+3fm8GMf/kJ+Ek8BoSlx0RtxNtTEXW89UTy7MdBeRGZDV8AxzB3ml9JLL1Vha21ccLZ6sEhSujWN6ItGrwmr8NlvUP/PVy7+UK9b6DqzAi/c72f6pRzNZNS4bWTafJEIV4Z1wEh2MnIxjbTluowSJrUndkSkLsFcfOL38Jb+yv4/DNY8cJ6CEHr7gxk5MNgpH/0EplpXX8idlIYE1bwnfxluhlJZiVN3VAn++Ddf0joZyKRj5ARaeHpwDt4s+YwUmvFKli4nwVBsU0WFZAZK21cr1VQI/iakDOd0IbyXPWZbG6QkhxBVanIFTSBA8atikRIX2Ij4QV2Y75EcyFTA1ijE1sID+nGpkIfx0pqh9xtdnBr9fJFI+DGfdJHQWnikn6caNvLpqQmyDkAam/s0QZTSJStib3Aj28Z4eS9pKyF5nIx30iZsBsbLxGoiPbmk1Z9/UjD+baIRYWbX0inK96tLXG7svxWFEOWgHve2ICcmYOU2NyRHOFDgJUd41rzbgkO/qMtXu34FkPqhrAqZJqnhArjW/lnaFd4FxiQK8YdHPWSMKXJUq0xLFEE7x6R9uVYyqm0tvAc9ebeA1KElH3a/IX13ArJ86oG3qAEfR9ZFO6sBBjXZiyfLQ5gLpambIUIuyca/eRxPoCXDfvBP0PVegB1xjbb6qeIMUdtzoC3TWs04nd3FI3zZZGMrX7N5LX16Mo1ZbmVJhNE8GmRfGFgo+rgjHqF3DV50l90vI/26HPemx3snnitbcSPWMPTOhv8ywjZUG9uzr3fcm2Ed7R7VbKJn74niA6+MdFKyY09JM7nc0=
    RABBITMQ_URL: AgC3sDW/JlMCkpBWx/U/zHHqa2AjRSQT8pv7g8M0oL8TinyYNHCNbXVua3dSW6cDDxUJKBSbn/cBrxplBxPfLWLnZlGHtRvvIfz1/GWR30ZSuPOgIfuCI+OiDbEEvLzoLHEsnwgOCCUzBVoSk7mSSQZB96Kld+qsSPf9pLP0JYybX6gCHZW12qrpFzBcMBgw682KPd3+6AAhXtMGMsNwAvko/r+wVpT5ypB7U4CzFUqxCQ6Y4raKT4gTPTPcGAOPURpGgmgyjOUZvQ7UISmMCGkZHykm2x7/tUH4a70jRK+V6fqEejS98SIddgiNCKoBAI4POtrlaO3NaS/hPFHBcS2b/oz7FtQF6fwAcZ59NdOD2OGLPZ4XRuuWJXQvbyy+Aq7MFmYDICHeMafiCuw4x7HagpLQq6pSPWS2sHek9JL/6fmRsubkaQ2vm2E91LeOPXXCzMgAANW3Z6LcDXd4NO/ux6LwoqNMYx6QV9ONS8ivBGJ4iGYShAJ21Vkw67bpcBtgob4xW5Bf4fEgc3K+s+6E4zXuqx2ctLxan4EOliNOx5xt06FGnPbpM2NBAWB3EghIOoIcDFzuc0x40qNddWZrSh9oJ1R4sz9kWH1TzjLHqLBrZP8zwV5gmAovDKhLLftZWLd/yCc7E5vl0Mg0cmhbRtwki24Xb/YXaooX7puU8X3cV0jRbMTCxn7pIXCA53a1AJTqTyIf1sh+XpOBmP38CRILsJ246GmcLz4tEzynVSgDFdGhZxdkSfuoS9Ve3JxNqBC/HJ7KtzKC8xp2wABsDFmDwOILM408KLvBWoCV3iEdnWiv5u1UcS0=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-dev
    type: Opaque
