---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    password: AgC15uMo32W6xS2rLiClEhUB2R857OLbuI+XFTccS9wqnWBZs/Li570+74Wj/Kg2HX6043pDKrNQMZ+AdUEYxBwj8NrhrAMb7S9xoKY+XcJ9J1OJpe9j3eXRnFe5HM6mqaE0H1csELaMK09L+7i8XAJoNB6yenEDPhJ65YCO4Du+ceqIiZ/HcdlFpIDo8GajA8x6+julZatA8BFckQUdLieghLPWmHZxKlBOreoUsRhfvvuG/7UOZhl8fiWhJj+pYCrZGDm+rFzz2joB0TA9mC7HWZOBn/cwTF+5lPtVDTEkYyY3jdiNWSrQUsL+j7n0wyVr6ReTocqtJzOUyfv7o8z45On1dgD9Bztcp39iIzzfYdA4XjQp2fqZC5Eo3mbphLAHd9P7nZpMM6S12Ae/rTA0kwXx5rlWE3STR7eKmqNCFkquN88PYJ1tazNMK/WxB1r3rAYTrCC+uue4hQ7jkVPqTHEPNuX+BTWUf6PAqqhdOunSGBG497Jt1hjFOlwNEvb61ZkV6pp42qIsHuP0biPCwTouN1YZHbdqeuYJ8ztUAJz+B9d+eKk0xdq9DFbVl3NDxJAG2T+hYdsRlUWOvgzzdGQgD6rkbROtNmin9h1QhVzEYUTmvPX+znhWMKZwcP8fuv/rSMyA+f/jvf8tWYseLP9socWiZBmwSdq2gbTWQxCfqoqKkCeqV+wHTnuEDOsGzTfPdrP1zKu0/hTmnVJ7iSTqlqZIR80vPh3K6HFPKmyXAo3zuxIwec+xrTsJVn8=
    postgres-password: AgBg9wrmmeIP44lcmKDk6SQEDfvQ7ge+lFaYjtAteeDZ1wi65R1ygi277dX+Cjn8uFVVhjQZcqFwNJNyAgPYArC6d7cDmDiuDDZAeBTmVWEKFnjzN7nZare5JpTbQf9by7Z1Uk+Ml6RQLRv/0wR1gDbmxbLgzJ/4VOWGFNV2R/zo+kGs6zjoRaCSIr5zz/g9mqXIA3Tb9o2sojpr0eRDEKniMFHg5noccUz+6Mer7HyU4rl9bh8JhwixIkhKA2YCaiHyec8kfWWcWkroHR/wit06LSzsUuvQ9fEE0C24+2VJ38cmN4X8xr3GRx1UIIOGKpx7PcG1KDVZAAoRC0DtReQTQ8eHY8TEVfaD7pwbQn0y3ZFaR9+GwxfEoP7DI7/gjdLXogiRRKBxH12yMCzhvZpm+UWRyd7zplFpxrf8rmEL2r3zu5vYKJb4EoUugPIbsoXIFFMwSmft2NSdS6lIO0iC1wY13Njp1JWz3KiYDNYKLu0k9v6wkeP4zkk+xHwFOAQJA69M8pp+bBVGJz9qNrkOi/y6i6aM87IXVb3OsqiNmCa77F3hzm/ziXJSL88zv2RfWEXZ4PS5arfQkBmawz12M+Eza+N3aIBGmO2I3pF3/zRebcSXYHgpqoN59H3otRSvLbKMvSN1psuwJzlFL8KofEEA2aTxDirKZVFE3DHFjGNl4mrxI0pgrjmpHMEqtDGgc2gIgNb9Yv9dCXvEhOpB96iPLpYdQuqzCoiF9heZMkY1HNybfuF7rFahlhjCg7A=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-prod
    type: Opaque
