---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgA1d3yfYBqGdaeD0gXpfc50UsY2c0Kpi8acMFbv8kvUE+Cf5jRweIZHxEREjEJXKCifTJDyTCWokrJ/xxlgSJ7pdUS0fZ+MS2OUmVbn1Gf73XJHjqNGAr3L7Y6BP9MeWaDPpXHzi8LVo4Vn7u0vIgz1QoqdnvVsfYv6fkP4u5Eydu0pbDVD/bFnkjU8rKjiSKPnCpXvXj5FNeIOFBY3NMjq8S2HpsAJJ+KETOdieEI6yZfUdz51uMSHl3Mj5Fh6rYy8uzaVSC0EdC8ds1YiMIXrtDOZZQzyToZWXpN6NcM58f1Q1UJ1H4xKbjHYZwN6a6Yvycj+z1SKz0frNWywTS68OLWc2i0ZJo22jOxdHaAt74M5+VekPnRKsDep/U0odrOw9mG0As6uHPOJww0fsM3S90rZpOOG2V8V40LfRqdv+HFPKhdTGidjhmQSDrkd5TrwN/HyxSO2GkfJAz3mzFftcUuixTp0CFsCmJKr1r9U0PexeaCyVLxvBDImevpqkKMWIM90TXR1kFcENLbDovCbtGhrC5kg7tJXLVC1Qt0US4EiEw2Ay1qPGjX829oX0NwcCkR4l/Ax794y4JgtnV7EroaOlvd0Ox+L4cE8Lm5E9WbFJSX3Oy8LY6ZThwIeg5YLm/QcyRrEW/xCTMNiC7pKUvumZDnpzIBuQZoKo8YurfQ2o5x08snmEMxLpYRHlY8na22BKeBAagHOy2i0TBfBB2N7czxJDgsq2Qnzd+4EtR1xYCILjEPEIZsU6Q5lgpxzePuYZZyqoOl3hOCHmjKpqkFvFuZmKfKO3Su2t9acb6DMf+rG1pNQekwRQ7xk13RlxHFvXYRi7uOwEXJa2squ7m1WKDilY5B2EmZUHiByhrtozbn5J/CxgC6b
    RABBITMQ_URL: AgAROLF0qbuJ7Y7eQNxknfzePyCyXOZI1WEWA8xxu9BOeAuVqg6eTfJorZyM0imawlc9q8emPyibu6TsU54TF9R5aplxZAtql0il4TIvVWO1YHtD/a+ao9mvxl0LwDv2BV5K3ZRMP+6z7VBtOJfB+eSgmbSjQzhxpjUjNWOAlyXglpnMt6LabqzAJgFvznjypq255fJKuKRHQMG4s1t7F8EY/eUtSJ3n59czUUSKgCf6vn8Urvh3xJoMVIo/CjNwdI23bOWDKAiden057f9LioNtGMjVKB/fvpdbaR3i8HdULkPpqaz1gPocjwmstgpMbmygtJz+NGJi4Iuo3ji2yqV5ZTUoHcpy0NAyLoaPl39i5RX/Kl4VOnWxoBGjM/v0EX/YtJQEaeG5OfSCCItm9ubJq0VlQsTyxMj/isY4kG1RLJF1k4LEv5INKJQa5XGm4Ev3PUymy/rRj1ons/1O35Ce4VrwJDJjrp4LFH0S8Ixztu1UgDh92hWatADJdI0HsOWbi+S7i5eQD8+eOk9eml7gZ74+BNbMgClpSnFxDp6MAiqMgKP8Il6Z7CHDJEd6Si36KS53a7qpTgdjgm/wDOWmr3/fgAXXicXfUCKH1+YOmIfLRviDO3LOjXb5Q8tGK986wmJoxV10Iq4v3X05Uzkt701/5Nz/RtBuD5CqC2eC1a41QVGV+KDYBkvel0AmAlRAv7ysETrIuFihdPLD6Oysy0vzZwicjZSS2FbujllScFr4frmNALkc18Peg+hLniPJUGWMfkAFtzaRIKANIbaDzPfN0+GhhuR2zQeyCEj84SF8UPKoPr2dSbQ=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-prod
    type: Opaque
