---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    password: AgC7e6TyCCzQTkcPdnyQapJFGjLery9FLnaNF4HRdXx9Nm4iovPgZdi1PUuQJ35VAnv5y0M4sp56Wt/spmkJc7PFRJ94WBL1OUCE1dTXsAI+jdFev/J/rHkt62VLTgZvrLQ8vOieRgNqWVaqWnkKU7qg3fGw6y82VWI8fg6wdLZ4uNkv10u2nJ84lMtVZGAdGvclCG6qgjZKXYGzUOTAUGm5kcLX0hsZZrVwUylsgMhrlXUcg338Yc8dwXsytwyRFP7c4S0L+ogWiPcORuNEk4FGqa4jS1WmjafGDR0R9mPQgWSA4yaBykHP6QUrBjwB8/RDqNRhME7wg6/2rQezw3Lw4J7pT+fqWoCKVxYmQ+e1rLJpWTdocrdYhDHI6bNG1bPzGC3ac/0EwzvMM7RvBljykRRyY8IQ7NjZN4cJlvLkc0uDEtzM/g6lWRX9lkwRju9wwaI0iabs3QXDsDVBlAoHj7CslMd034sc1BbPLmfZL68lEc+opcq2AB+wyvWxjYMiPXlFUBQopoT1jtEr13qzNT0u3CbxUvCB4B/x1Ayar2nwV4B8g8k0z25+uJTKMeNnYWn2fEPaSpuOIN71LYoOOh+4OrkiLh3YbjrjgWuaHUfQvaIph4C0vWO47Qs3zGNjIBLfYT+6KSrWAgpvGrNBH+D7wl08ONaKkWAyCcnc0miAf1UXflGt0bYBC7xyvhhQZ84iPUkZx0qTpFLiwXrwN4z+zZWw1hmb30p+Z+QJRPrnjPz0zPksvXWCutml3yo=
    postgres-password: AgBqe41+sWVKbq7cQnDsDYsMrAwj2OvkLHM0aGO3PZf3VviipQQXRlkx0jzWOcV7sTWzibzJ+SBNY3GgxxUbLuIF5FFXkNEK3w9aR6rqxVtc1Ahqf4+zJaJ1jLNL444EfMQaIKYB3Sm4KZe+rHa4cZJI7xs1IyNzJch/U3Q5Fva+VjdwtIMQV/EbgTZhVrrSoGjGHKPwYzirHRe+BJJic5JYaWWYKDFk7jhpPigMwmsE6kvLzdtHmjtuEyMSRQA09azgJgDT2eSDjaMqWbiaNyonNeh6sR0K/jXJAdFC0qbRepFeogTM/t/97qIergUdsUbBXSxqVjSUEo6267k3SdgVUTSpPzknn9tqbWA6Yuc1a1EAMCfc7FAy4UzK+Uqh4UqZ/zEhzO1nECs4iwHhdZ8r8f9/9Dx/j82lwZNrUAufy1U1j58XuLkl4g/pGwuNKbQD0xnfzxBH0LxRmjkob9B3z7T1/+bT1sQ7N0HmrL0ptALKKKiPC6ejreS3wc9pmJST1/JBMIN7VaA3Owzv/1lBaXswejRzsZPnIwjoIiChGpSrYuWm2HMr7EhRsGNcQhMz0AHtCjuNMvDEP9H4mNtAWoDH0EOgPKYcgBs0XPoeEhQ/9CmWWpzmrr/Nor/oq9s3dG+wiAxHMecMm7dYlgUaiJw89WZ6zrK/xRG4rJIfU5Y6OPo6pLT0704+kd9RpcsOshPCO74TfycGyEzNHDxignOvHX2ibrhr1oPXWdvioqXQlU6uSQ4wazpp2YCdROo=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-dev
    type: Opaque
