---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAbgQNH4S4KrRwU9rNhO+pMvVvPrZJzRpxxt9EwktQoQ1zv2ynkcwEGND2AUNsSJspZy6dASQlm1pAshfkUddVM3LQj3rQrNhvuC15kHzFVrkZGV0wBtLqSJGRe2XyvFac+BVTAcfLsMGu4XrJNm0d2kWuxT9i25dmqwSmlbraJM0d9Q9hUejwF9dy4HhO6foGWGs0W/9zULDWCyIf0iE+3beHrekxrgRfT9z5IX0z3hST4Vh/GFAMgz2syFzyGOqNw3tBDwI+Yld35O5WSZh6Rz9dAA0QcHpagJ7pzQ6QBC1ngqUR9uLVv9o7EtcripGUvKTzv+Hi2T2YbxdDZQCFZ/99io6Chp3L3Lfkw8Nq3Ip0lIzYm675Zi1EI6+0wdTHjgYdNibiCoN5nks4jBwrijnwsnLV49F+BlVqCX9t6chC2yVEtWIaa3GjiygTUxQK2U1eRttkCjNcdYRVkOJzWIxRwfyOvXPOdGqWTQIH4U18DuqNZPSllUprFv4F95fs+EOOqVhPuc0PIvA7zgVeE+FsIVgQpeDVW9PTWw9abY8YPpcUDWHvScmwXgCtan4CFDYZUu0c7RGnpGxBqiasAfeJOr5Et39x0bmyccInbox5HTaQ+wf5R13UeFoQmESB7TERFY0PuxH2O/u8rZK002FQ5hwVyExR74h4G36HT63LGp2B9ThkC4TKztWVJxMoxNdaLrunSUHGVA7BiU904hj3nIUAtGwe5wCUWK6+9oeAtMUopEZRR
    rabbitmq-password: AgBDNez4Dckv2zCBLmTle21MwNKbAkSKBDLZoWV5QYn0hGC/+Sb1c41EvTVew2h477cYhhFWONMopcCCInX5fSL5iWJAyZPswsiRBelBhD17HbP5p7LhTsfpMRNCgoTb3E53tIHSfjU3PyBhdPfXgN1r5zsun6Bv5pz8k1QCu+5AQwkGmI1r6BgDS+KI38qLbmEVxWZRTw8mkynwy/q3XRBCESdwAs0rvEhC5wV2r6W0EYWeDH9EAd3s0oZUiOaJb3nX5BmU1wc7LmwFWKZ6yq/KZFmjhEvH2wx32YVdDP4i+BhVnVRz0/rHKvvpTcswF6zAiPOYr0z/c2JB/NJkkQx64cyI4nA2vBelHp6CTrBC5Kq2Wj/ZHUuGS7rAtqw59mHFzF340c+RpH7QYy4Re8kBT8aXHL0KEcs1UalO6zQ+TDwdR1SNpf2PAJgiCPyDbBWQaUvFTJKgEj9JCD9ubfitC5ogjVz+lsWO0OvKi96N9hrxScVjKHBm3yhFDmEJYt53hrm9696NYlep9/bXo+1AXwIKgaDxfk2gYmP2LjsEUfvoI9OvqXdzfh4GJA7HYIE4zfsyZgholsqVugE6GAk+5n/KsN9vi43EEuu8u96ASkwRcdn2GTJq54TnYw+LEma0zISKbPtNvUkMXZ2M5469ndHrq1BdJshHRlMMwhyTe6d74+M5G7mp2fkVxCW6FBJsbKAvpVs8bpsuQHmxcqicE78u6tEBVA9ljQh8Rhuwo19zEUpj3PAFGFZESNiLgQA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-prod
    type: Opaque
