---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    password: AgCSC8/4rliqbqjjCNQiRSAHpvGXWw9ShHWM6X2dyUyRrpIINJ7owvzrc4HQjovZoSqPP7RcpuwhX3Ok3FxOCZrMCcKUFLVaITgc5SxC0PbHgKFxn9v9U7eS4/ufHr/DDriEk7wewneWn6tmkEHic7DeReSdTKwwbtnn1uqiP0H4/pc39zFZznIKWFXl9HaFMt+rOJ9m4KzEeh2EHiemB7FZtKytGAasHWCmXk20nc7SL5KrinAYpC1PVW8k6s99ZaRY46GxYdcc5mPN4BHNUKBGwDF6xPGtT63svde73B5NACEoMsrNoieDI5POId+X9cQkqmE2/L05fNnOnBMugVa1GblbdYbNE7W+GfTbIOWad4SRYoDhOVEDUJdrVag9J3JBe4xAlDaZ2T1H8ah3Uc26I1pzRoAc8k3+/fRl4n2F82plsVf/fit15YHg0Q25vbl89rmu21KFjZ8d4A9WrhVifc3GNauM9KYUl2jkNE26+E6kChsHNjRf6tzA6kFdSRobaTDxAGZyEX9VsnFtgktS+RTQySOIPhNJqe3XhTzysHVXwerIAGBnDmjMQBDu3qdfxE0CBBkS7mO+ZWIlE3rEoiBM8CuKAro+JoyWPeabOQUmTdHsS+qRVTyF7OAV7dO//m08YWac+XWjC7sJv8YcyHC/rgzqHF/VrxiTNhwgdgr8e1TwwRiBhk15OCACymAfR55DHi5z18ACknBOGbJlfElPoM25FsrK0+e+aTdiyJvixuQGBAcJn5ismQHo6T0=
    postgres-password: AgA/HAchGuUpUDCMkS3iIFYJ3vB1jTyjYnCLrTbfIsuyAVrxljJAFY8r9csWcHwJwj42d9ChKX1L9LTl8LjHW8/TjNB/gFr6chi0QoAnGl+LlnRJxyP5bSBzRtgB3U/kSG2C+hHaiqBsBtn/hPI2Sz8v1aizMcaHzrHing2cGLlQ39HsnlOVYWHiWSzRfS4v9hXuHXH2Rxy6vtZIJdKcxickS7lETtNcVN/RHjFSvDlti7OkbHrF+kXxHTS1puQMXRzdB7kwZGXG3lWFicXmp+iIbuNWOZ8ckcVpku9VG5V3oDY/s+RZsVnwSr3z4y71EYlusxYf8NwzZQNkXDkycrp/3qaM73DZCyEU/9vOBuQHZtYKLj/0XXCWDbH9Yu24VAEluqe773xQTplBJ6Pfcig7La2isNKn+ZwLoy1qFaUhMpeFnU+MKBu/aOZWWkQs87uBHnfLmtEEpWK3McYChXBjd+2FRUl6ELxsiGWFU8rfLxaQTzx2kGZtR/71uQDptjIk2mMRY1Dy19810dpDeb2EV1nHbkR3XCBFerKpuZgI924PaHGrGn5A90PwwGCf3vcGO0VHi5UNzds7Gvoj/wOheMt+n/codg3aZtCUEwSPp9HNrq0ipFi54g+wlUoRpf29QtUfCYfuNfYuDnluLOissE0qItQSbASKHzREt9YXKiHWBTJnsz8gAYf3ntU4RQR1CdhgPCC5IYRi8A5/mm0oOY8eJaJJp7dpz5P3yEoLhoqGHKP1XZnn4kHaAJjNC6A=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-prod
    type: Opaque
