---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    DATABASE_URL: AgA1VLEWOheGt1U66sqJPPz66dwEhDA9vT9Zqdit4wFA+hs07Tdo6HEnflwfTpu5g9R8QNBrGIPqJbHv5+5MNRHFg6dL59sG+hbAjQ8N5lrgUuAccixyAlO5qZUT/3wrQfoD4EixPEBuzIcK6monwkG1CFWYZHNHwIcA9PiZd3+yj2+cbzn9cQN+C9HbqbAPzh4KUX8meV3hzw5GqcI87v+AQl2w9MccX4T/OdmO5KlE/4hA0cRxgLZdYv+ZObdJ3JWP4RI066EQCZTeO1uUlv4au+SUC/AIzCkZqKf7QBaG+YvSTIYfovREysqkXuKIMhPiGaoWlTFY/gE8dN9q5ShtXQF10vjQM5aSbLEANkFSEcTgp68ppwTkNlQec9M8+4aASsB88h/WqAMtOWtSTp3H+Y6QOgu2ZaVhaqTGh0cJcLXXFHbfytQdq9Nfa3kGx5xcAVCDhvtbPIbiEQfV693yjS5cZjz5ueTmRSr7J4Lb0mIgGM+Ouqns/zeHb4/tfqVKlBwqDoChQX0srQKPqehzQ6LKIp6olHB2ItwUwd4mvgN80MYDuFz/24lWf+17HNMhdDH8LK1VL0hzEzG0EezU8qXxzq9aBPkfMJ3ShPoSxqGfhSi2oBOJeutVi9GUyILPoXsi/QBnWcrUmtBXdkn8sSof/EnUUyOWy0zfEg4TKE+Qrk4gvOnx3+byYmGDiklW7EdawcHOGcHKm1S8cB1W3Hh/kobHwBkT/Wojc8Ct/yERC1CPWJhEWFw0O2aoRjqX4e8qnbdbJnCQt2ihQLE2UQnrxoblU+GHXAaHkTn0m2cvyRl0Q9I2EqsBXvDOPsrLjCBF71EJ1M7vE7G+qnAc4kVJbyrLHuiKmXkiqkirEflX4kADWu6IBW4=
    RABBITMQ_URL: AgAUox+g6GE830XNMPqWfB7vn6FRISp4YAzhwvLmVZzZxrjWjV9SUNIh3FEhZ3kZNJ7WGXHoRHR0QeeHQLV1atKDfHrOvgi5ddMh99F5pbaIfDYBQxHCVemzg9UNntjao66SAeesUQW8Lp1QCF52S5LrVtEEBQkNzsqGp5iWFJsYfJbah6nq0VZddLGK4aWZ6HRNMrGKRmojbgWgm9b/HZkOGUvN8NDpb0CzrMUEp7eFj0lqjcd0QxlH37DkN6qa7ORafufrLhYma2stZBwPQ4HyVu5/ufKkNXTRu74wsROtbJ5NuU3UIJ0Fuk8XSKmTPXxAUPRAm9ayTqNdn0jfyjPXusn4CvVQ9aiRDL/FWym9MGk9cTS1x642SLAKgKYOTc/q/XD/ahu2RtT33SoH97Su2Mh1uNT8Kazc+Lovoi2ohy2KaZI8dtffPZxPNhDxmWNVRdX+bhF5af1geOW8mjGYAtu4PUywMfq5em77Rbdd6xoLtASSyii9DVHgbOvTTk44J22niGeu1BElXkNFcXWCFiBd1mh24pH/2lPVLcxKJwtWtgte9efTrCEjMcO504vfzSm7xfd24lTvUOW1zkgkC2gsZ8pMVM+VnrDOvGYOAgxNkEgH8ROkHi5nNoNvALxl/e6kv+PukMzg+6kZqC5pgXaPGLnY6145dWUYpDgqpJDRn1Sx/1UrAa84QIn33H95CzjC1AFGc7vqPxr+vKYXAlX1TVYC7c62ART92fsrlWnoubxNvi+LTn8icyXLCyOUS/DzMpgqzcAz9YkfHjvIyDysI3aHMc1yuzb5z4HGIft4awXGKvUEEec=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-dev
    type: Opaque
