---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    password: AgAQoqyBGr3fcFmVtFhYhuPukHdxmmFgA4QDrNhSl2TrCul6vkzuN+q7OU+xnsnhMTgiGZx76H6zqSpZ/7O1biHCMoSoGqCOzJ6KdoV5KW1yhphmmvn3FFDt9nWk1/4nf1FkYGZfHwqtH3SmZAOdsJL5bSt8Y+UiYTQSWFDBx1GCFO1+oh/lXxPwsJnYqVx0/yYo6I763wFYcDkouhk9xpNazLl0mSRRupbiO8dRSsu1EAx1FgiUBDmbio0bc/neXP6EZjpEyylgxNXXmi9YiF9O7cXd0PynmusIlNuNzhFPNfS3ZJsO/yBno1m8vaUQyBDfRP93QKn92CrBHCrD80uIzrRfoG1rG1BbkUjrNR3+gBPn7NcttKKPh9UYmz2hiiQMpZ6E/7Tkhz2LQuz41jSQjmuHbzvWKLynw8o7f3hUcK76gTXK9vy4f+j7UQlMNj2UvTXqvA/AaRdAs90Mi/f+s6OY2dF2MJ5G6jYyxh+v6I4V73yyqUVUPxkJnmjzGGmVy/gkUrCeectQz1wkwUr6oBGVimXvbKy5XohaEdaJHrQpCoHqwlq1iADNyGL8/aj6B+HsdWfc2N47QUTGVQqRCx0oMHWSsnASrmKgu6mk5a4B8t8VW9q62V77JiEyooCwOYr0b4cRXfNMIinauBdoHvceuo1TfNHZXt+/M/p8hQAss4CvQl6YV9UIKQ68eCED8cAd74hvvtbbSZcMyELSVKHc3PD2afRIQgY0mE28mF/b3xKzUfI0DrqqemZ32gw=
    postgres-password: AgBBMiOm9uccUPWgs4yqJKjTf+mywWS3GCOKFkTSOmlpPyjviympSL0TAnwZkF6UCW935/8DXfVOM8+J94nQxKLDRPOBNN916BML6G+CBPNd1qgJmeTnFs710raWGr/MjLsXkrEl61d/3O4ntuQOn9fnzoontnOrQgbalYCwTYWzQMDW6Cyn4qVQbqUW3SSS/2gVsc190cPZsWoOZTf1q+LgD09cS5cbbe/G7KXOrHDAOjq0a4cCqZTtSCeTBDx8FOgbEsGZHZ0tSzC3lOM/HB6b3X9jtPJrWEuKusMP4CiY5NjhjBmOOgcjbINQPRTbqBLldbVIWoP7Ke9Mc6hABQLdeH9hf+Mq369yKVqbn2kbeXUujyde0FsfBzkWeoqjIYAKeQpEnefP4Gv40KRrHRH89VfPLu600nMhfKBZQMqjUMdhIwBP6Gbplo0VVmpf25lOYNynt5aooq7A5dhSPHE48OqkzBGuEG+fh8d1dAY0g0EU72jHFgSPF6x3tf13xosyf1BiS04Hvvfk0xLHj816Lp8R03mNJHZ7eT9G+2X7p6aw3vYeGO1JCvf66eH7fd9PsfIVidZ1edeeXrGKm9ubBns1VIXlXQTSCGPPDHKBEAOg0b6s2Bf4C7KKp1yuun3zLpMs/+AAg2nTTlsrywS464rMgRNJGIbQLwg7dZo6sYirGMUX0064BcWb8rVQPvU/dwJCjdmcZdj9HMpeR8eZ3y13e8XvDOGL8sGotUG83nXALspS5poPn03AUfJLVLY=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-prod
    type: Opaque
