---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgBU88czVVVTvCi83HkH+c+jZwfX0cWOe6MWLh/aCdwybWLvpTwfq/B4kHbDJ8q725wsHyoXRgfoJjkahjImw0W/L/DonXdc51U/J4Zl04JmIIfuWSzxOIvXJNg4fZxV9VwpSEPg3CRe9MDR89ZhxAa7Whs8QfXtsHM1cyb4F0UnitNxBxoNgrhQb3Oyqwxle2g4D4bqt02OFkhSXER/e2fDZamFLvlelHq257h1aCTp9MSWbOZcf1Qo4lVkBuP710KYMG8BQgwOe3vK55G++X/UUqZVuRN9Y9vkMNiJ+hlNa8boaWNLqXlsrf6bz40WtR80HiYSvrM0L/JktyWOMq563yHOFWu8WLC3uhZjhB7Wa13GmBsNZ/LdAJErKrLyavtqiBjw76IXF1NSaYGy5/lEk8YJ7g2NvK+iwM14MHuj/p22MI4b5nLIs13x7k9R/tEYyXPLOEJybs12OZkW6hhUr901V7XnFtnpvn3u+v204WmQHht/HwUbDUY6wZ0MnVo/ifK386JLePsKUOHhFeAIRnB+nxCRO1/t3Bmap56/pKKI0bzKH2vpA5oEzOy9Cr73xampSL3evKhryO+txSxnLrvjJEokNl8a8cfMK6HvkD4x3UnrzTRshc5ohBLg6Ib6t6OkYWC9LRJODhPCfiuvKI4/e3Z9l69M1wR5BKPGuFDp7u+fHVY2SUd504uMaTk86C9UcP7CA/14vNsmKYidJ4wmizXZ5W4d5icYYS69RdOiXzD+HeWA+ZsIMXYe3K9m+42ciBWcTTSx0qt+1oRzwLbqSnnny2PPjvqmcbTtKwqGVNymziXTgyS5dd2UkKW1G5JbNrZc04ZU5ULAMCeH3KNrKQ8uF6YcQI55xLlQbXpOa60LWOF5OjQ/
    RABBITMQ_URL: AgBhQrCtZbI3xbZ4RM/aklNrj6mX4FdPiOOiLkN4J8IscRkZXBvWFNVG49b0wbVeMeKfFxPglmY958FOGeDwhFyDTuELpdBNCVyPtRcaFpFv6dCtImrizdUDeouj4Lzaqbf3Ph2xxA9VC6YMGMbQoR9UbrijTiwICBKmakowGLMWYOmyV8yqiyAkIVqR6rn9ZT+bJgL5LVF+UI6hsjHenLrny6vfoB3z4eWSjSoGQy9DIlVFcpWSHUkneaFNKrWLc3kbOoAFesxcW51cJrO4kLsR/I+Rrk+gp7qZXgU4Vpa9oDl6kuZAHWDZfjTLr4WSbLqGW2WoCpZQP22jqhTs2/tco4ldZFRQas8b5zEzeR/u5qegZc8ZyH8zRnMNrQjSEJWrC+ZuX2rpaWqeYnvgNCswCQhOyx0qdmt9J+dJv95ieWQG4bknoK6Q+2DshggHuXcXNSD2wucOarAFyBti8LNKqC8O9Ssl/zOcyak1vq3wgZMCDQt0ZEKLUGsVy0aO4M+URvJxcIA4G7cltR7YSwA44L1CCbezHbanTm3LOYD9PZjwq3Ax7jNS0lwhS9TFS1iPJH0ODxNTjUoN+FGpkaPuUbjkd/ma67XNs4ve9zSIOhS2SmKwzdzwIe9husA0Xi76fC/ofe2Tyg1kYRPFHrznKWEaGXylRnSnS2rnQJcox/xkStP4tm0L7QFJ7knbO8d9wKQjepiv7ANkt6imQDpMyq4sB8sBm673Qg374MLaGpWlVxzl0gfTnR7ZD7f8TyUUfWDVbttFLkR43Guc8ioyrVMZ5YPClldETs5limWAypYjqanWjLU6uvo=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-prod
    type: Opaque
