---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAZT3wdjRPhNMLCiETvssq03kyIlmzpOEBCkY7JqSlEAkS+8y0PzW24UZPyEilXxh3/PvHG9n9e4YF0AyrymhDBmGMDPl0KhsRViKYGiK3+ap99C69Vw3JUnH1t9hYEmUr5yQt2pkKzPG3KvN4YhmZzTA0TGNSKWcoLpI4Km5xRPRYk7DUmyK03HszbCnffs0lxbcvlAQ8JAAOq/7FDRp1wwiZ831KVKUoskMcf/OVClPoFgCSFGcWAkcDA27HgETZXww7Dpm+Zw2Ggt9zSc5T+UjNnEPEknQhXuFrxhXWDMtjLNJJdbBfn+co6hq4pf0nyUkAYNhoNTBFEmdecogj+YD1/YkyBVVSL5N/CxrXuUAfVeyr6QuZQuW66VUGOJ9MVll4dJ/oCkbhWvaLjfSW373M/TKwJ1+GbgYUqrxM1Lmp5YKcg1FXo0NVzd+LCwiH35psiUa/5FXTtK+lhC8DmIIbO4C5Jenj+4TT2itKA6wCOiuTh37tXk9RDbW965mvbCMAd9EmsEOjPhHv4P7yT9LkUFMP976LyWJrRxFKIT//jXDYGO5DMuRuXvkUC+IgES9128Itl67INBPdheTj2RAR+vdHuc0poItX1aatmDzzC1NF0Ffz6SlPJdyoBZadFGQLzwncl7xg3xsnKpYPVKeSB/frlDk8TEAd6uaU7QCp3tR8yGh56JOEFziQPEF439daQnZPRlFCUMunpEDz3+vfzoy0Phb9kmHDjn+3CQiTCB35Y4cwz
    rabbitmq-password: AgAy+IVvMLT2EJtivoaK3ZecGJ6YZaynBNsXLOoLRhST95OsRlq3c/tQELAzPsXohGIRBth7IIopYqhkFqCSYXCn+gu5WwVq7dz3PmDtbeX8uwqYJr5uF2gvCsJW0hvKpwJqctDwGPeuSORf9sqioQgWn3vf4L1e4C7WU/JN4lLsfQs3AOaDOFalS+18JwGhj5/Otx4aJ07mm83OW6wJj9W219eyZFuGHmwNkpuxkuuOfXZJ4axY4Oe65ZRrlXU+sNr5MYbZh/U3Ble0JEdr9mIbvkzSpSoYCkQpiFjFe++hDzylEL6TPRzCzIudnVD7YaoU+jFhHl49hbiHRFehErExYocC1Rlv5HcKxA/wUfff1yaZnnFXZuuDNNkULfqgosQSilveqUx8hHXXuTFa4BU6BgYHfUh8Kc/GpRLgnwWc1jHO/aFp+jUiqd+Cmbjq/re+Qpgmlwdw22pWf69mSWe+L3jzUh+lQpUNvAxfA4St4BGAsmTzXzUkCORizeyYHQb4X4pzKtKhUToIsLasS3zPaj0fxLG1DjL5t4aFQpHFiQBaxQJd0cO4oIewBlTYcFozd7ChP2QVmVhq50DWuVtwWs5p7U5HNmJo+cB5cvu7G0RgrasqmC61ewXFcFQMnkeTJgzvGkYQWVIaJvFGkvJVZ6f602xu2inaMvQkpq8bkzg92Mlq9YYcdo+72ORh3eVMN6dTbaYqd0PHEVigxSz4A/xW4D7qIhLX6jGyFO19W7aH+64Ef47R1nMe72d2z/A=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-prod
    type: Opaque
