---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-prod
spec:
  encryptedData:
    DATABASE_URL: AgAu3OKcrm9KYrMKinq8xBjnCYENw0LK/PkXxSg4nV2enkbDvgUjQdUGdfACu4regkJ4BYVmQIQJLtwtyLXL8PbwaT9AmfFk/m0jHB1890Gkss/w5NgSnxIwzs/OcNvskWFceD8zCrSHFC5djP8ILDTHH0ts6gNHrwLc4pkLLvJZH4LBhEYShan3spbtYzQ8JaSWg+pOrX6DeZ217scvw5sjjznNGzh3xEI45eFYpGC/mL+ES4T0QB9Nogb53AyKyX3mnl5l/+DGvs1pbKNDNEM2cstdayl1VWoTdtkRSZ8ZQXW3UhyB5cMTs4NsvpsnnZGUcYLB/Ce+xx56FwizI8JyZjSJJxNItACh5bUUym86FBwTHVa/YFaT3uSEZ7Jy+b2N0AWPM0WNHSmB1w0dH4Yfphs2WpnLQs/uasSyUVaZ6KFPDf21W6jNK2xilo+rFsdGsu3UWooSA2a6j+E+ehlmT7ezDAEVHCl0utB0lfpF10Udv9zDE5STKe6tp21XhY+t55crKJpBmPo1RyVGZCZKqtJMTkssp5bFoOFMdmAEbbfXJJQPeGA0M1ZmIFQX3MDRlfH6imTAZ9hrnS7CaqGu1J++MGpIGtykGB8FN8SHSHrkNAxZR2GUlN6aFnsBNgINRzgnhdehfvtRVIqGhWLtm56lW8RTMQcYygytymKOHz2vY4+y8dWGt17YJVLQ+3o0KdXKPbA6sscNWAJdMFLaa9zSugREidJwdXnWCR9vzNi+tIkjUXG/vQooPgcf2PLsM5ixOaTVBDR3blxxSJ9zopxV4fwm5fXdIJrQrkSPf6O/mEkJ0fI2rPPgftNin5dF5IIoNFO8Z1WvK8n2KphHi+++wo/SZbOAv84HtJCPQsKv2oxGFEY+lcUE
    RABBITMQ_URL: AgBBN1nIrkCxAsvPNuqNDYJtVRfBsC5Ih9DpESnhImRgbMJlDCrUbt/tw3L6GSAzbj6apWu++NkTAF4IzIAtKstm8qSfDK05IGxLD95BTEvMM0kcj7IwvbgRveVdPSkTLZOpK7hYlAsVTsasapWBPoYLjrZFFnm01/nsou+IJDgRRgU8eFUzP2sT1dTSz1FuD6lonjJJk0K29lmGQWZMYAdHUucwTgUp+px0ZXDnn1iE8Feiy31LVZ70bH4OFWKNCI8d3HQ6+whJ5HedTpgdQYYFzY1lKOZh8pmCQrB27Bn0JPXI4XZiefY+UVzEEXA+RNtPNmpekCcVydt+rC8aKIz4RlFHVXLwYrcQ3kYZgnmjhdB1VQAv2JQEJUVVGdxhKha3C3l1J3JNURpaJ8w7H5J1V3neuw/ZwrMsSym7XlPoyEhs2NKMu6JCjvOPMKoOYo12PPjZKnmF1QZ9FsrG3EO6NxG0ji7G/BGzTcVM0XHj3tqYPobTf1uYc719Z+D/ujs7tq8GHNE7gYNK+gklTOHq4xiXlfiH98OhvtC2Md440P3Ve/IgUtb5dSsIK1jEMQdZQzgiXKVFx0NB01L2rMvZTYLeXe99E+FCwvLw6JhkcXaGbf83OlURjKVvRepYppjD63670pjOhOdo9pPYvkYu6M+33hE+k8DWwPLzClOe55q2BIiYwOScXo7hmdrK/8hVNb6kkujT9tgN+prAB2VjyWHlpUrDKBJQUZ4OVN4xqfFgh/pEs5rdmQFQP70bT2JUOf0e7kH8uGtFfC0LvQSJZq+K32p7TJU80WhK3xC+gmzotuBtrSp4RXs=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-prod
    type: Opaque
