---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgB1YqdC9H+sz95l9a/C4G3ksWzjSLOu+5NyQCvFqL7JNdIcYfc+k0jHGpwITgNOmhdVLGoOcLd+WHaPpyrx+ULVnn6OqbK4q8qCv4J6MyTPbJM+Sp//R1xscOLv+qHGnSCXZvpvjs/kjzBQ+0/MRgGtAi49H1jVNW0Z5j/dI6tm+sJLpPCCCRUChXD2nGaT59OxV9Vmh1dB36y8pJd6tvvT6biLJM78xK/pUUawygqc8ftG0FYHZVGegPx5/gOlFgIuQro3JDe8eWO09Ox9ObhtWCNfdGn9AaBdyBP39BkvnZBFAtj8w2/pdtYHux90oXQ68R0iXsW7XeBgBR75V6WPDpqJ0bhlGEJoET660ReHeXe9VF+6hfBl50IiZClkyMz0FMwzOBLxozIkC6e87uyKZ7ITAQEu1Ym52fR5MRYNk/53bwzvDOr43IdaOZ8tDww1eKCs0FaTYpRZmqIAbbtjMgm0Rspi3pK6UM3QyykswsNKuWGZk0tOPnIM2jVeV4je+SnYPmHvmZfSkoC3mUiH+f056ulMxqUMEmLulxP0JE0Z77zs7vldAHzixUw36UE71KAtO2E5cSAyS3S2FRfFkFbfM482yQS0PtdvP8Oi2WJpurGcmOmCdwipRpeZXW2cm1DccoxLV6yS/h8J4CYj6Nm5M2r7IpX46k1mcuiUEkZCIxy0CsoVb98qnWt7hq56RBf24YfiICRLRG86/X87j7P9pNTAkMF9eObXh9FJV0AKjbYrJsvJ
    rabbitmq-password: AgATfVtdy6itpYzEE+qW8dtidk9KzKoZnrS3A2qndmzLwNIDTPJIZsu1jui+HoLA0VjGHc+d4PmLch7Tk0rk+KuaG/YBdErs4aT2brbZDU85/I43f8QVfcprPBTJQjQkuRXC5R4RlxC4lNflnINIKCY+GgY3hUYoaSksZHhomD0Ou+h7VtfUclsfFYjPmmOKu8FLVsSho4w0EqR4D6QJYYK/d+SKwKVLRVdM+CQzsXZWeGUSyoqDk1d0wuARylGh23/vyWDoTGzkTNvci4L8wZWgYwQTyLmuct0nsqA5jjxHXhe6pfpm9SDMuRwajWyDbYI5Q4uhLMzhtue40alhi9Wt+clOdN1JMFro7LNckcokDB4NedxB8f51XM2kZct2E2MKvGrTmxzckydImYQRjq1esDleyo0SLulc3g+nIqNOO6qAjdA07aZ1wzu0WP9FOJGJGtXkCql1/oQpudMo2blk5QSuijzGEeSAtOo9ZGGXLg7vs0DphXSGtcPruNEqdly272T3Oi8Rnx1nLIQtJL6LwRgcuMSA5ekWoJJfooQnwQIwxgWe9vCOuLA06/R8D18LwwTI5Dxi98ZhQcmcW3D/+dAY53szTXzN+iw13ripWv+Bi378lp8ItugII9BTB4Gs3AVyuy0RUOvrDo4lW4v9CEMLNgqQCGl0w0sars5lYd1OpuFaGdc/9Jo+Ww4kgqSMLbo4ZVV6RGg8P2mrSrb33qwY55To2U3JheCX47F8sqWfkKTBV7MTumcC3vuNmVQ=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-dev
    type: Opaque
