---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    password: AgBdzwKrobwvpl4jAIUQnHJfKBuYPV8i0QYeZYFhLK6ZSp9Tc6mkTtfwVhHNzkAqIYeRosHEy+bmvsDHSK+kKsd5zu9Z1WH1wzIp+afVmblBzNljgod4tAMwE/+Irl0/ebIvbGJfn5rGhPRxmi/anU5MdmA/dsmAS7rcVoHQkasMz4y/be67Ih2LqkbJ0590ll7cNfrabNjqSaVDoWanCRKMqTL+bEUvJPRi8ByPTa1KiHlprbLtFzPqmzqu1PyAIIXW2u4ZMO/T2vN/Wm2NZjPPvRH5+heJm6h9acWRJEA+pFuQdHAnpljBiPQWjltjiSRK9tIfLzwtIOyht+dR6KIrjszl/zf+ZlxLl62h97ph4B3p9J8rHnVTbHwtS3z56LDdVi7Jll2VPfdXZM0Tt77CiMASNaPLDdQ9wExVV99PTZiXWtRFMM3nMHADPHBKiEObGq3Bi2ylGp+IzKN6tNLDHI7URZhy8k15m2AMtXptBaZCCBrf1UUlLLRH5OpfZzyQKSafS0K1Tuq/1AKJuP6pkE0bGuOEVrfu8b1aTkNT1Kn5SCRfL+86LOrYjzegsGulK2FreaRIiTdC378oETavcuQZbjbtBI0qrOG8YznH/RuAoB5oTvHHK5yTihucE2M2NNw2ajM+WkmF1zD2aQAja1ByUG/J069vSBPZimTgiEU+wz8Zyq/tLUSePPYMASq6LSqd9Z6wvr2XFLcpbcQBsFF/P1LuKLX4Rd2u1V8ou5ar55r+7c8kl9mOAm24o04=
    postgres-password: AgCxWb3o7nc6/8LLY+6f0yL/87in8mrj+8J6PnX00MRmStFVv7yITqUIEGRBYYlbGOUssCbinMxoJgirXaFdW+sjJ6+mOEDLBJvNbFkRNqtiHZGZbnlqggI4x17NlEaacU7vGh30nm7DzRj3aouWotDKUdYYdbjsvwtQxeMUx60ezGs2Gwuc/U6EerAHQ5RzLHC9m6kH/Xca1DMWCRpoKtGVM+q7nVI1tqcAi8CynWSJO4UvThbFNM5/0girz0ndzrrBindZjqWpp/ZBaPboGHHcggVXjqly0gqV5llmcg6fYmpZnKVISZ52ffs8e+2SNEM0pgzwKrx3hcnqtJzvV9TbkkZtk8FTSY2IW+Q9ar/gXynZoAgJvM3XkKs6ydlxCAD01bfMljoXl5vVqcFu2PJxIFcBc44v/f5GAfpiXEVXTMVLe9e575k5cy17fhTgk+7u9dFK5SXXERF45xxIDln4VtqId4pqAY2kZQr7PJA3K8lDLsrW35wkKYhRPx28KA6qEH3Lx5wSh4D83X7mRBCbJVnuUljqeALr2zW3Og+2t2X0e0F7WRPqcPesQ66d2n4bwPh/Xh385MAzwZYR4Y1gLe5oL1XvMe+lvM8r8AVFeF04qXHGm2Y3tHGuFQWQHI2tQjTM84GV0FO0nV/ePTvw/o+ykRFRF+SSCJqFVQVUn4+gy/Ms/hWDHKEmox6EQU1Y7qD7ba5YgM3R0/8KucO7nN2h+GNRhapQZgIgYNIZuZY4ZjWGzvxGQev+oMBa1KE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-dev
    type: Opaque
