---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgBg2cN86XwaAyl2uPHDwj75ll5V5PfBxCkr0ThFPSCCBjU/K6OTdP9X3HBwlUZkeU/dogj+/CQ2rJtLgSCDVopjoFBiQTglrS2OcuN0WbvoTrYu1kxNkFOWpdFY6tELabyy1pgAopS59byq+joKpjSDq1B3cMg7nIt7r52Q5CvGKeYtiEzFSsPCbMSdLWrCaSvNUbCoTuAAuXsTj4v7AIeBh+hfrghXAkp0OzgHd5JhqoS9iwsBDuVJF4dYfXZtiREV1eiLuYhSOoGOmlqYk7KiC9heGuj/UJwPE4D2DqhnViUjY8UlIoEplzWXOWsPIzr9GRP4J/aXXgKuF0gD12xWuCOpK7HSUGSSo2TeYu9DhpyQzRs6Jqv7plVhQ/QsOi4SGT74v8vsR/aUg8j1cjSd1VU5JR6sk2ZswPvNBsFbyNvG1vgNTzH2jJvHFQYRtEpUtC9aj34Ts8/cv7vzUJkZpITVI+9A9byncW6VHUvbSG04NeuIrSMZmSnRakBLYT8xjhZmWNaFIXpcQ2vwmyYaE2pkv2zOXFiHFeJQgCWEvqGBHogVGagxX/EJsphuPGDstTWvayKnX0BDA+pFZmSk81R/RakrOZgP3LA8JW91250OgjIIQ6CwIEekoJqJlt0gKe0itxPc8CDvcmgp9fxzhoubeby3gynZzKtoD/LNwt6+DfmnaguyDz+KrTspZS50eWrfbA1cbGgCV3+FkR08CacBBwDfhc3h0DQ+QC+tptAFXEVCPoWB
    rabbitmq-password: AgDCGjWsJXmYuAqpJOOnuVV8Fpaq6DSTNXQRqOLbZ6o4FR6ONmFCcHStThE/T+uWEWZPLjJgk4/fKBHn9bbGYWYuonRVXbffsBhyrCaAmrdbTHVmU7u5lGWyp4EO6EDved/WIRb+FzalxdtE0/Q0b3kfRN0/suv2DVWifK4ra5UTj66ooEUB4+9QoNBliE57DRuK59vm2Ow6xPLBcdk6Y6S35SnB5hQFWeFnoOlc0s1NbBtH1TqaSSAeASnTTjmbjqEArMbdJauDsVn9ewW/k3YrSniRqc0y9Qri08WBvBH/ym0r14t7EoBIc9CyGay6A3cLLqQNwefSYVKTkfeTLEsvM4cdzLvGVn0P4cjRJURXWK+e8fbadFj7U7lKdj3szTcmr3QWrg/tngsDxQCT6WR+FMdfZTkdI2PzyOZey1UMX+yh6AkVvyRz17IkaGx1JRX64gGNh6yLPwUovxQjbVHhECRlHGOli7o3suqTLRQ+vd3lSXy+2hwdRSZao1W5iNCdxkxPcQnpwdsEhXRlobbdANTle/2LKeJgiXjltqz02xH/WGjooEDVvxmoRwQLH0eTQ62v9/zI/vwfo7fzhs5Ah6F5EkIYhnqTJa0STm4rHLizZGbykpGqcGPptNptlR83PXmss0kq6DBHYDBSi1RBrA7PhyB+ULIxTHZxP9YHRRAtvFilgrWnsWCDCh+PVdeZmIAoiSGvUBrV2boSz1q9eWjkMzA5PzFg/GdB+p9JTDpg3vlU1PtEg5jLIRscxi8=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-dev
    type: Opaque
