---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-jobs-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    DATABASE_URL: AgASgNx+Y3i8h7qslADTf6JAM4EagEUle2Ii+O+r1sVY53V9Ta/VHphhZa/KM1s2zoQc5whHLzh42fU4AFtorc7tn0LB8eMqak0n2bkXOkTcmUvfI65BbF/b4ALZC6LZgj4Cx5YIA+BX0qdme/uvsbMGqq5OltoBGYW7IhxjMzvocSobW94FvGBQLC87VrpibhESFV7pSj76jX/mQXy5kSsDzDwVhArvvuJ787tUrQRlZQdwGWjKpdjSzhL1qoLm9R/kzKLr13fDcMqQ23z5FjnhKourOOlRkpcQFTy37VpcGPeHSS5pAUTnrAP5JqjiRhBs8+o2H0r53wFXVguM1jvKtqBvyNQ5zTzRXP2+kQLSTHoFM4KB0zokSmDZu0gmA9xF5vscs7WR5rU2JJEyRJ6hCs1EA8gHD1ug1Man5OmhGd9t/+2fUKVLp390t292jPUMGjf9D52xs86pTMfACPzHZbGaQy9rgIMhnu5A6tOKYwWMF4jrStOg/Z5oHm6t376bv89QtbQhjCrWI0TAAeywhlH+xbOL0jx0xAU5JGj7RNbDJziVUvvNJiZ+cfTbS7ajQ8elX+lnX8rX0Li9nDE5N/nZab+432hvTg2IdloEFXDdMvcatqydAY9aZ3Whm6z+4cGzdHoxV8H6DfqvV5CaecINYYgA9hSOWP/u8zuMK3Ogu831hEh1TJh956uAJzImsQIz6mq4u9UX3UhfuqveI7s0R9lnXAeJ68y6QitXHhsrhb/v9caxGap0y++a95urdHhIUXk1+/e2vlQ1qCOJLIHVGWYuupS1rMGrdD3VKB+1KpuJ+l7VpuKyJH8EM75P79IYO8BOzoSg8Au64LrnXF0mNIIx7Nyl1A9YfKOR6K9LRScKImR5QTg=
    RABBITMQ_URL: AgC4F0gPgcwC58oSkvOIXrHr8r1YB7iIysNoCN5F2Sg0uhJ/eDZfAMD3cBZmVWdQnVJdMTQVmrTdXcmTKT9x+1bFfvY4Ldy6x+VAtyIQs7bDj64ZUJ7dYl1oKyq2KyVv+HraGyL8wNbJlqqxo/U9m3RBxNg9eWWkUdKU/fBqfCWtKRse7JwSsXoEClgphrJXw6+pj/pfD+Wjkf++ieZ5nbnlIRcatt+J2QXVasMCwhHAWsAPonaA04zSR7KnN5qb0nx50FUV1LQG1e+bfcvMNoKrhWnPoOb0C5KVK/rIYiRzojVOpkzw9i8vwuFpFpTzCRX1bBt3ozuldS95EdF6tQX5cQWRg6baekIUfwHrTM5v6cBRxOWaWxA+VQbkv66gN621Lj1nHtF6m0EGTJ67ubr2c/RVS+U5AaZFJ92T9/BW3+dVp0cBsmifCkWv+TGBYOHpCjKSiDI+C0aB94KnHpBzcS48sKZY4CeEu7Qo319ebQ5hBk5FDJlGhmNxFRtcYSvt+AsoBPk+hHZnj3NX1m1Kq/xJyrynFdMYNuRiVxmc/3a9QelyFbNdk6HhK3Y9OwusPIFbGEZtOa3fNAjxhThAyMxuvYvZd5lHn0AsQaC6BWT01vtu0XFBST9qexiQiZjgoF29ZmZg1qWGWT34Zoqpd+UFxKncQPDQp2tGa9ctbcrZMN0JftwuDqt5ZxuPrh/h/7hyO0HPPteW36J2cYBkcs+m/DLWfxodKeltQ2g0oooPFR35p39TkRvf7RDvnXEsoY+yFmagzNhUp40V4PsxVqHNXot0vcNXZB5ATs1KRsVChTLAVAKSD1E=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-jobs-secret
      namespace: sa-p8-dev
    type: Opaque
