---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-postgresql-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    password: AgACiT31Jt29cXnIFh3fTjEnHV4s0VbybfmlfkjpRHSN3X/0nAmh/YwtScIIqrvxff3XtAXSHtKy8ysM58El7clPvObZH5Zbbhk3ACpFCw2gSFuuAFXvF0jfq0/qYH/yVVlHiYW9LXR1hqby2yma/vhEvycXp7rfByzbZmu4uab0v5l6aWLtt9Bw81hwIpPGq7hUi73yBP3KCVdEo6gqU4a0o/L2ADIF2vlV9y0WlNMu690Jb6qGKYHW9VCE9e3KPVOJ8L5nxFu8QfKSSARD76M3a513wxfCbAek92gAcJO8SW26li1etCE6Px3dAhNFLm3YQeaRoqCpwMw2EzhsG8bKQP3blJLX7ERcMmrFCqbEwYaOIxeWYuKYU3nbogbhR1rTrRRFsb/1ec03KOp592A0nXY6R5k38zeO5EgQhweu2fhfpVSgV45lHhoKotXo+6y8qRFNmG4N5PsCYAYjKf1m/pOuq4kDmX3oB+jZ1uMcXO9NxhLa074uguM83jsG0AxWC7pjGGcjMAInwcaBeuC1JO0jTaduQJTiRFbYoF4RXTGHDLVSyyglRdxC2yuQP/L3YM3WI+S+KIxGorl2PX7pefBbxST4ENCEmhm8hF4bWYRvyDeiGcVAtC2tsD3ApBJW58wHkhFAImYGOiHdXUBBtbcTyU3LzvBs0tFBkR3zCu7Q69T42ZjRDqLBT5Gyy2amo2vw/vIalJAZrKoMiV3g6ELpIszEm7FeOILEqA2wG+wvGlEeTrRo+z1XA1kGEio=
    postgres-password: AgA4CiILD0Fh1GOt0leeiVfquMU1DuBtLp5mgun+f6W+zz+077nT3mGQH5levsYTXomsVG6wvGqlbBpLlHbsJ6hcS6u1gCfTDoL8HoB7vrwC0COxrSOGMmVYWmuCyphD3YWkRz2UQi15qhFcH12lel/kBVRCK5Az5Vc/1DewZopRSJMpJ3TNJneFSbv3TIwl4A1S0gZ5APM0yZbNdtTlr4nqxcDylG0ZNR75IJ8mgKVls0cwyvSwJRW1fRh5wAncJAeZUgXP/CBrN/OY/5UuwZoRnVzi1oJLRM+Bl+kj+MKeyKI27fUMBO+ApmL8KtcmJ7BjOwsnS/1A4cvznmuObHDemKQEqZuAJPsSum8ym+m7XERyGvmUCBnvR1Qdf/zRfT43NMHd9b2/4M5nFwxDFlaOM/FwZYKhH5/F5i9D9eyHFCd2dohLCrtXkhXpqggxGC3svpxw0hOYAfMnOeYOf8zHrg/zXP4Q1G3UHi5BEKjVMLvcAsVDDMxuAB/MQhwc4McOA/P8xukBFo7Wm3KwJsBlXk6CymSBWRqITfS6f18xAyY0tYqNGv4Z1g6zI4F/24mWOI4uX6DQAXBwAg4ZmkJvL7dDm3VLgsORtt1YuJIWqA0P6AQK93E1xK7e94PU/9a7GdvEo0EI/nvqqZd4NOE7LSt3srkaQisk0XNnBvC5ZCo0qNJYeUSCUliRmFjwflxlSKmgBgv6mfaxNT8H84MywPnAgK+spMn/MGQydOGU8FLnV4nUUkMq+3cwQ2ptXJ4=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-postgresql-auth
      namespace: sa-p8-dev
    type: Opaque
