---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-prod
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgCd2CEBm1ZhWKn+Mu18mOXWngWzONGyyA/3oVKX/QWrJ0ZPxOrXYcC2sPOj+3lFlzmyMuCEXrW02QrIIsZ+NVMW5bD42UvRzzJnPiVWOssmyMqjyuxEn2ULPsv/PlILnLdKrVEKRgT2cJd3vt9YAnQlAO/3BkSmrEvYo5IU4HMaTOv5l3wX8XpRj5cbqp1cD3nHfYMw1VtIXhyXCyKxDZWe0aADuOxN8VisO9oImSeUQ0nIJJZvHVVpm+1hJIsCipvkUobIQOqxrwbW0kfq3/3pKs7IqsD7eCoL1LHS6vnoYZs13bdqEdMl5/CpyXYnnJceh87zNbiqMJfiBbEwIrD+C+aXzwGKinqSt9ZzAgyZW35pIFHl2DlHpNHX4WgRQxsuAoln2ZPKu+QypewCaVXMDXMidcj7qKRvuil+auirnkpkj+nBOxQBNByx5YFaLulmdf3Bccqrifrn+Z7OisDFyoF3kJRYfyPFqHM3ZEIh5q+ep7PzVeOxw4M+kYDdZIFETi/T5LyEUiJPrGWN5C4XqwYc5nOn4DnsF+V1Us6RyN2DFcPUVEeDeuYk67h33/cBzwh2AoRMnzv0GYqP3ZDWTrcdZvnESdQRpgx5AmLxhMPGrExhdsG/7ThEnKaHX/MyPeBEA3BJd1FtCb3vsrvfatKJjOskzJWlR642zhcew3CxNqnABG51LpByJ9uvpYmrGYSQIAygbeZqLOmaXTH+mlrNgGMsH7GLB9l1qp3lzzdbNv6SWaef
    rabbitmq-password: AgAttS5unqpt5MY/ZtU2Kap7BbH2suJpEjWQnppPJmiHXknYR/UiY0fUy73+FJY4Kr/n8ZPe3eQMEonCAnSyqLM73SscYslQKYhJ/3DNF896/xsEhRojDD699eG4psX20JH3hvnyT1JTzOogzvVJPol4HeIiZ36w59BvQuoyum0g3CTLlTxWwuIn/uSeWAoWfU8dNCP+cOTPD76sQZPu+6UcRcQNehIHfmCUKFPmHMNNgoa6gBI1bmfHF5zF7oQBdas81DK7ujQbRJjUmjeC2g/JGE9QsAZBwCIPCNrngoyaZYVHd91KIJUeRj1LelUVBx+kM4KDyKYyzSyOwOr2KQm6iVjaLDGXSu5NADxG6aLDd4vSVjTv3cZ4G8rE9gin3MNXFxwyINixb+zPy0YXljlsBTX8afgpoLqGMgRLP8xEo36SJ9MRWrZ+XG8ryeX36UgrYmB0BHd8Twcj1NDVK8+cfdPkZ/xGMb+g8KYZSEIBsm6v1tXXGzXdL0XFP2HkVJDssrbUM3q8CS7Cz3hytTvwaOCG55r/EsM5t20guODiJ27W0XYe8v+dhnHizU9Cgv+/7TGaVATLzDvWvrOaVvQz59PnSIeAhaCCTuDxmrzu22uIzwzSYhJWiemq7vzVzEdD0wO6PXrLF62A1b2nysFCDi8fwCYVzn9RfM0FgyZNa4AY/vagTg+C4gv+M3GZ9ICmi0ylwGOaSWmgq5ZjQAt2jno4kuqQBPVusVMMEpOrA+ItMJKKGiw+plYoiCBnW9Y=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-prod
    type: Opaque
