---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sa-platform-rabbitmq-auth
  namespace: sa-p8-dev
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgBPAXOvDNnqh++N93m525HHaXhu4elFVnK10q5kcD/B+NWTFt1lEp9CvobB+IrC6GWehSFGYUz9l7EH16aQuKrEuLnFo2fUODYdEYdpQ9A8Z94h2F3DdU44F8Xi+JG4ze//wsMXy+k3Zvr/zEhqjCJP5rksrvcW4NhnuUi6I7sxgOwdIZTN0v/fAFrcu82mK4hKYC6qLuRmhnYuvSnjq8suwBHCN9l3jgKBR9rdqjpVNDd1VlWJmVgeZnybdqmpSjVuF7lZMNKttX12bz3aOsp1EoPbUeKAvecGjPlaFUDjevDBkoDnWP32zkKPtnRm0wCpPyFGXhJsgkmkc8naWkNQTDXbhhasshpiJuh6kbhJghIp0dfKTWSoveT0sTdMIOSIqBtGi68B0TZAeLbet2oOk7P2ZWcXuhgsD25t0u7508ciyihLlFJo5KJmQn0RBz67G0LqNdFHmoVHMzudTd9Ofkk9V6zOojMlI8y0wWFgj0xmIZPy7iBnU2HEN+GoBXp7BTLNXma1sSF5Ed0l1IS8RTpJJ1wyGAUYFPTR4bPhkrZ+Ve/YU6x+KyQwrZ/e6yn7eOO8DutSDVcQvp3PfurtINjQzsHy6N4QEI6IaxMri5MQyb6IKO+3VfmiOSENzkAldgWgheIF/HAv/Wd9GC0vi4PZjUr3v430u+ys39R9EMI6phyijtW6cCWzvKenhbZSVeFUpFlQIWTsB6fVcs+kFkjNfIhO1TRTo9w6VRc94jIyn+3cYy7I
    rabbitmq-password: AgBdkBeumuiI8tUite6I5+5DLF/vSzwY9SUzlXzhZNbUjkmLgBFlG2oKRK6PS31MBad2gPy9EfcKkrACx8np/o4vY4arYnSjDCfnT51bB5IoirOR+q3qdHdZ4UjrKJMn+1OkWvzyjSIimupOmpFPEC08LYj/+2oFcsZaNp7SqID1G9oOl27dzHibwVbkLrOXFAOcptY5BieJ/h+yaoNJfVlb8cnKbczYHT0/u4DwJJpNPtmRWQ9Qng6ylwDrBUpjKhwlRl9W48zcEtIMuKiQKQqsFjlJtclD4C7o2HTWIEB0Q5GGXhzJn1Xr2GeTvYqlyEt82yC47He32A3fEVjXqR7AUztbtKTG/4wpu7MZwzbwiC67yTMLJ+Pu6ultku78blqNYNLldP0NRwD9xHdLjNuZC5ClcML0WuUy4zMdfBGwQsT+oYRcBlynIi3ns0IJ3Rmv8SGgeIEhLQrkTLwGoIGKKmJp6rAmIupYM3LfxURU4bh9bBiZUP3WSIDZHdk7HwspEmdqVlstt7Oym6b3kjI01cCGyfUMee5YY/nkBEtXEhAN2XfViaPgVLl9UKQKKNVlgz6yD9RrBI2VUUKMJBj3y2aFwgDpHpL6AxQYK1xDy7LF7ok5AuNBJzrnpqfD6uWYz+kJDJNCSVeuMUjt/r1MI60a81MtYq8k1yr0gNGriPtIt+9hdU/ZW69AmE6dP6aiKqIRetxHZBDAGPY2F6KS6XU1fL9g/XZOA9EtcPvr7iIKtLOHkIU8yfLtm//22AE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sa-platform
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sa-platform
        app.kubernetes.io/part-of: sa-platform
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: sa-platform-1.1.0
      name: sa-platform-rabbitmq-auth
      namespace: sa-p8-dev
    type: Opaque
